package com.calebgo.gitstats.generator

import com.calebgo.gitstats.ValueTable

/**
 * Calculate the difference in commits.
 */
class CommitDifferenceGenerator extends PostGenerator {
  /**
   * Get the headers generated by this generator.
   * @return The headers created by the generator.
   */
  override def header: Array[String] = Array("CommitDifference")

  override def valueForIndex(index: Int, valueTable: ValueTable): Array[String] = {
    val currentCommitValue = valueTable.getValue("Commits", index).toInt
    val lastCommitValue = valueTable.getValue("Commits", index + 1).toInt

    val difference = currentCommitValue - lastCommitValue

    Array(difference.toString)
  }
}
